parameters:
#    sked_app_booking.example.class: SkedApp\BookingBundle\Example

services:
#    sked_app_booking.example:
#        class: %sked_app_booking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
