sked_app_service_provider_list:
    pattern:  /service_provider/list.{_format}
    defaults: { _controller: SkedAppCompanyBundle:ServiceProvider:list , _format: html }
    requirements:
        _method:  GET 
        _format:  html

sked_app_service_provider_new:
    pattern:  /service_provider/new.{_format}
    defaults: { _controller: SkedAppCompanyBundle:ServiceProvider:new , _format: html }
    requirements:
        _method:  GET 
        _format:  html

sked_app_service_provider_create:
    pattern:  /service_provider/create.{_format}
    defaults: { _controller: SkedAppCompanyBundle:ServiceProvider:create , _format: html }
    requirements:
        _method:  GET|POST
        _format:  html

sked_app_service_provider_edit:
    pattern:  /service_provider/edit/{id}.{_format}
    defaults: { _controller: SkedAppCompanyBundle:ServiceProvider:edit , _format: html}
    requirements:
        id:  \d+
        _method:  GET 
        _format:  html

sked_app_service_provider_update:
    pattern:  /service_provider/update/{id}.{_format}
    defaults: { _controller: SkedAppCompanyBundle:ServiceProvider:update , _format: html}
    requirements:
        id:  \d+
        _method:  GET|POST
        _format:  html

sked_app_service_provider_show:
    pattern:  /service_provider/show/{id}.{_format}
    defaults: { _controller: SkedAppCompanyBundle:ServiceProvider:show , _format: html}
    requirements:
        id:  \d+
        _method:  GET 
        _format:  html

sked_app_service_provider_delete:
    pattern:  /service_provider/delete/{id}.{_format}
    defaults: { _controller: SkedAppCompanyBundle:ServiceProvider:delete , _format: html}
    requirements:
        id:  \d+
        _method:  GET
        _format:  html
        
sked_app_service_provider_add_photo:
    pattern:  /service_provider/add/photo/{serviceProviderId}.{_format}
    defaults: { _controller: SkedAppCompanyBundle:ServiceProviderPhoto:addPhoto , _format: html}
    requirements:
        serviceProviderId:  \d+    
        _method:  GET|POST 
        _format:  html
        
sked_app_service_provider_show_map:
    pattern:  /service_provider/show/map/{id}.{_format}
    defaults: { _controller: SkedAppCompanyBundle:ServiceProvider:showMap , _format: html}
    requirements:
        id:  \d+
        _method:  GET 
        _format:  html        

