parameters:
#    sked_app_company.example.class: SkedApp\CompanyBundle\Example

services:
#    sked_app_company.example:
#        class: %sked_app_company.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
