parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     dev_skedapp_site
    database_user:     root
    database_password: G3rty.

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    recaptcha_public_key: somepublickey
    recaptcha_private_key: someprivatekey

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
