sked_app_consultant:
    resource: "@SkedAppConsultantBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_core:
    resource: "@SkedAppCoreBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
