_welcome:
    pattern:  /
    defaults: { _controller: SkedAppCoreBundle:Site:index }

sked_app_member:
    resource: "@SkedAppMemberBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_category:
    resource: "@SkedAppCategoryBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_service:
    resource: "@SkedAppServiceBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_company:
    resource: "@SkedAppCompanyBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_booking:
    resource: "@SkedAppBookingBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_api:
    resource: "@SkedAppApiBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_consultant:
    resource: "@SkedAppConsultantBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_core:
    resource: "@SkedAppCoreBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_search:
    resource: "@SkedAppSearchBundle/Resources/config/routing.yml"
    prefix:   /

sked_app_customer:
    resource: "@SkedAppCustomerBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
