<?php

namespace SkedApp\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    /**
     * Get all active category query
     * 
     * @author Ronald Conco <ronald.conco@kaizania.com>
     * @return Resultset
     */
    public function getAllActiveCategoryQuery($options)
    {

        $defaultOptions = array(
            'sort' => 'c.id',
            'direction' => 'asc'
        );

        foreach ($options as $key => $values) {
            if (!$values)
                $options[$key] = $defaultOptions[$key];
        }

        $objQueuryBuilder = $this->createQueryBuilder('c')->select('c');
        $objQueuryBuilder->where('c.isDeleted =  :status')->setParameter('status', false);
        $objQueuryBuilder->orderBy($options['sort'], $options['direction']);
        return $objQueuryBuilder->getQuery()->execute();
    }

}
