<?php

namespace SkedApp\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyPhotosRepository extends EntityRepository
{

    /**
     * Get all active company photos query
     *
     * @author Otto Saayman <otto.saayman@kaizania.co.za>
     * @return Resultset
     */
    public function  getAllActiveCompanyPhotosQuery ($options)
    {

        $defaultOptions = array(
            'sort' => 'c.id',
            'direction' => 'asc'
        );

        foreach ($options as $key => $values) {
            if (!$values)
                $options[$key] = $defaultOptions[$key];
        }

        $objQueuryBuilder = $this->createQueryBuilder('c')->select('c');
        $objQueuryBuilder->where('c.isDeleted =  :status')
                ->andWhere('c.company =  :company_id')
                ->setParameters(array ('status' => false, 'company_id' => $options['company_id']));
        $objQueuryBuilder->orderBy($options['sort'], $options['direction']);
        return $objQueuryBuilder->getQuery()->execute();
    }

}
