<?php

namespace SkedApp\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyPhotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyPhotosRepository extends EntityRepository
{

    /**
     * Get all active company photos query
     *
     * @author Otto Saayman <otto.saayman@kaizania.co.za>
     * @return Resultset
     */
    public function getAllActiveCompanyPhotosQuery($options)
    {

        $defaultOptions = array(
            'searchText' => '',
            'sort' => 'c.id',
            'direction' => 'asc'
        );

        foreach ($options as $key => $values) {
            if (!$values){
                $options[$key] = $defaultOptions[$key];
            }    
        }

        $qb = $this->createQueryBuilder('c')->select('c');
        $qb->where('c.isDeleted =  :status')
            ->andWhere('c.company =  :companyId')
            ->setParameters(array('status' => false, 'companyId' => $options['companyId']));
        $qb->orderBy($options['sort'], $options['direction']);
        return $qb->getQuery()->execute();
    }

}
