<?php

namespace SkedApp\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * consultantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class consultantRepository extends EntityRepository
{
    public function getByService($serviceId)
    {
        $qb = $this->createQueryBuilder('c')
        ->innerJoin('c.consultantServices', 's')    
        ->where('s.id = :serviceId')
        ->setParameter('serviceId' , $serviceId ) ;
        
        return $qb->getQuery()->execute();
  
    }
}
