<?php

namespace SkedApp\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConsultantTimeSlotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultantTimeSlotsRepository extends EntityRepository
{
    /**
     * Get consultant slots
     * 
     * @param SkedApp/CoreBundle/Entity/ConsultantTimeSlots $consultant
     * @return array
     */
    public function getConsultantSlots($consultant)
    {
        $qb = $this->createQueryBuilder('c')->select('c');
        $qb->where('c.consultant =  :consultant')->setParameter('consultant', $consultant);        
        return $qb->getQuery()->execute();
    }
    
    /**
     * Get consultant slot of the week
     * 
     * @param SkedApp/CoreBundle/Entity/ConsultantTimeSlots $consultant
     * @param SkedApp/CoreBundle/Entity/DaysOfTheWeek $dayofTheWeek
     * @return array
     */
    public function getConsultantSlotByDayOfTheWeek($consultant,$dayofTheWeek)
    {
        $qb = $this->createQueryBuilder('c')->select('c');
        $qb->where('c.consultant =  :consultant')
           ->andWhere('c.daysOfTheWeek = :daysofTheWeek') 
           ->setParameters(array(
               'consultant' => $consultant,
               'daysofTheWeek' => $dayofTheWeek
           ));  
        return $qb->getQuery()->execute();
    }

}
