<?php

namespace SkedApp\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{

    /**
     * Get consultant admins for service provider
     *
     * @return array
     */
    public function getConsultantAdminsForCompany($companyId)
    {

        $qb = $this->createQueryBuilder('m')
            ->select('m')
            ->where("m.enabled = :enabled")
            ->andWhere("m.isAdmin = :isAdmin")
            ->andWhere("m.company = :company")
            ->setParameters(array(
            'enabled' => true,
            'isAdmin' => false,
            'company' => $companyId,
            ));
        return $qb->getQuery()->execute();
    }

}
