<?php

namespace SkedApp\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SlotsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotsRepository extends EntityRepository
{
    /**
     * 
     * @param type $consultantTimeslot
     * @return type
     */
    public function getCurrentConsultantTimeSlots($consultantTimeslot)
    {
        $qb = $this->createQueryBuilder('s')->select('s') 
            ->where('s.consultantTimeSlot = :consultantTimeslot')
            ->setParameter('consultantTimeslot', $consultantTimeslot);        
        return $qb->getQuery()->execute();
    }
}
