sked_app_consultant_list:
    pattern:  /consultant/list
    defaults: { _controller: SkedAppConsultantBundle:Consultant:list }

sked_app_consultant_new:
    pattern:  /consultant/new
    defaults: { _controller: SkedAppConsultantBundle:Consultant:new }

sked_app_consultant_create:
    pattern:  /consultant/create
    defaults: { _controller: SkedAppConsultantBundle:Consultant:create }

sked_app_consultant_edit:
    pattern:  /consultant/edit/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:edit }
    requirements:
        id:  \d+

sked_app_consultant_update:
    pattern:  /consultant/update/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:update }
    requirements:
        id:  \d+

sked_app_consultant_show:
    pattern:  /consultant/show/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:show }
    requirements:
        id:  \d+

sked_app_consultant_delete:
    pattern:  /consultant/delete/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:delete }
    requirements:
        id:  \d+

sked_app_consultant_reset:
    pattern:  /reset/password
    defaults: { _controller: SkedAppConsultantBundle:Reset:resetPassword}

sked_app_consultant_reset_sent:
    pattern:  /reset/emailsent
    defaults: { _controller: SkedAppConsultantBundle:Reset:resetPasswordSuccess}

sked_app_consultant_reset_token:
    pattern: /reset/token/{token}
    defaults: { _controller: SkedAppConsultantBundle:Reset:resetToken}
    requirements:
        _method: GET|POST
