sked_app_consultant_list:
    pattern:  /consultant/list.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:list , _format: html }
    requirements:
        _method:  GET
        _format:  html

sked_app_consultant_new:
    pattern:  /consultant/new.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:new , _format: html }
    requirements:
        _method:  GET
        _format:  html

sked_app_consultant_create:
    pattern:  /consultant/create.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:create , _format: html }
    requirements:
        _method:  GET|POST
        _format:  html

sked_app_consultant_edit:
    pattern:  /consultant/edit/{slug}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:edit , _format: html }
    requirements:
        id:  \d+
        _method:  GET
        _format:  html

sked_app_consultant_update:
    pattern:  /consultant/update/{slug}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:update , _format: html }
    requirements:
        id:  \d+
        _method:  GET|POST
        _format:  html

sked_app_consultant_show:
    pattern:  /consultant/show/details/{slug}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:show , _format: html }
    requirements:
        _method:  GET
        _format:  html

sked_app_consultant_booking_show:
    pattern:  /consultant/booking/show/{slug}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:showBookings , _format: html }
    requirements:
        _method:  GET
        _format:  html

sked_app_consultant_booking_show_to_consultant:
    pattern:  /consultant/booking/details/{bookingId}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:showBookingToConsultant , _format: html }
    requirements:
        bookingId:  \d+
        _method:  GET
        _format:  html

sked_app_consultant_delete:
    pattern:  /consultant/delete/{slug}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:delete , _format: html }
    requirements:
        id:  \d+
        _method:  GET
        _format:  html

sked_app_consultant_list_bookings:
    pattern:  /consultant/bookings/{slug}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Booking:list , _format: html }
    requirements:
        _method:  GET
        _format:  html

sked_app_consultant_booking_show:
    pattern:  /consultant/booking/details/{id}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Booking:show , _format: html }
    requirements:
        id:  \d+
        _method:  GET
        _format:  html


sked_app_consultant_ajax_get_by_category:
    pattern:  /consultant/ajaxGetByCategory/{categoryId}/{consultantId}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:ajaxGetByCategory , _format: html }
    requirements:
        categoryId:  \d+
        _method:  GET
        _format:  html
    options:
        expose: true
        
sked_app_consultant_ajax_get_by_company:
    pattern:  /consultant/ajaxGetByCompany/{companyId}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:ajaxGetByCompany , _format: html }
    requirements:
        categoryId:  \d+
        _method:  GET
        _format:  html
    options:
        expose: true

sked_app_consultant_ajax_get_all_bookings:
    pattern:  /consultant/ajaxGetAllBookings/{consultantId}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:ajaxGetAllBookings , _format: html }
    requirements:
        consultantId:  \d+
        _method:  GET
        _format:  html
    options:
        expose: true

sked_app_consultant_view:
    pattern:  /consultant/profile
    defaults: { _controller: SkedAppConsultantBundle:Consultant:view }
    options:
        expose: true

# Removing this. Breaks ALL links to consultant profile. Can be added again later
sked_app_consultant_view_with_slug:
    pattern:  /consultant/profile/{slug}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:view , _format: html }
    requirements:
        _method:  GET
        _format:  html
    options:
        expose: true

sked_app_consultant_booking_day_print:
    pattern:  /consultant/print/details/{id}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:print , _format: html }
    requirements:
        id:  \d+
        _format:  html
        
sked_app_consultant_book_out:
    pattern:  /consultant/bookout/{slug}.{_format}
    defaults: { _controller: SkedAppConsultantBundle:Booking:block , _format: html }
    requirements:
        _method:  GET|POST
        _format:  html
        