sked_app_consultant_list:
    pattern:  /consultant/list
    defaults: { _controller: SkedAppConsultantBundle:Consultant:list }

sked_app_consultant_new:
    pattern:  /consultant/new
    defaults: { _controller: SkedAppConsultantBundle:Consultant:new }

sked_app_consultant_create:
    pattern:  /consultant/create
    defaults: { _controller: SkedAppConsultantBundle:Consultant:create }

sked_app_consultant_edit:
    pattern:  /consultant/edit/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:edit }
    requirements:
        id:  \d+

sked_app_consultant_update:
    pattern:  /consultant/update/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:update }
    requirements:
        id:  \d+

sked_app_consultant_show:
    pattern:  /consultant/show/details/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:show }
    requirements:
        id:  \d+

sked_app_consultant_booking_show:
    pattern:  /consultant/booking/show/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:showBookings }
    requirements:
        id:  \d+

sked_app_consultant_booking_show_to_consultant:
    pattern:  /consultant/booking/details/{bookingId}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:showBookingToConsultant }
    requirements:
        bookingId:  \d+

sked_app_consultant_delete:
    pattern:  /consultant/delete/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:delete }
    requirements:
        id:  \d+

sked_app_consultant_ajax_get_by_category:
    pattern:  /consultant/ajaxGetByCategory/{categoryId}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:ajaxGetByCategory }
    requirements:
        categoryId:  \d+
    options:
        expose: true

sked_app_consultant_ajax_get_all_bookings:
    pattern:  /consultant/ajaxGetAllBookings/{consultantId}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:ajaxGetAllBookings }
    requirements:
        consultantId:  \d+
    options:
        expose: true

sked_app_consultant_view:
    pattern:  /consultant/profile/{slug}/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:view }
    requirements:
        id:  \d+
    options:
        expose: true

sked_app_consultant_booking_day_print:
    pattern:  /consultant/print/details/{id}
    defaults: { _controller: SkedAppConsultantBundle:Consultant:print }
    requirements:
        id:  \d+