parameters:
#    sked_app_consultant.example.class: SkedApp\ConsultantBundle\Example

services:
#    sked_app_consultant.example:
#        class: %sked_app_consultant.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
