sked_app_member_list:
    pattern:  /member/list
    defaults: { _controller: SkedAppMemberBundle:Member:list }
    requirements:
        _method: GET    
    
sked_app_member_new:
    pattern:  /member/new
    defaults: { _controller: SkedAppMemberBundle:Member:new }
    requirements:
        _method: GET    
  

sked_app_member_reset:
    pattern:  /reset/password
    defaults: { _controller: SkedAppMemberBundle:Reset:resetPassword}

sked_app_member_reset_sent:
    pattern:  /reset/emailsent
    defaults: { _controller: SkedAppMemberBundle:Reset:resetPasswordSuccess}

sked_app_member_reset_token:
    pattern: /reset/token/{token}
    defaults: { _controller: SkedAppMemberBundle:Reset:resetToken}
    requirements:
        _method: GET|POST
