sked_app_search_query:
    pattern:  /search/results.{_format}
    defaults: { _controller: SkedAppSearchBundle:Search:results , _format: html}
    requirements:    
        _format:  html      

sked_app_search_ajax_get_services_by_category:
    pattern:  /search/ajaxGetServicesByCategory/{categoryId}
    defaults: { _controller: SkedAppSearchBundle:Search:ajaxGetServicesByCategory }
    requirements:
        categoryId:  \d+
    options:
        expose: true


sked_app_search_consultant_timeslots:
    pattern:  /search/showResults/{paginator}/{serviceId}/{options}
    defaults: { _controller: SkedAppSearchBundle:Search:showResults }