sked_app_api_get_init:
    pattern:  /api/get/init
    defaults: { _controller: SkedAppApiBundle:Api:init }

sked_app_api_get_categories:
    pattern:  /api/get/categories/{session}
    defaults: { _controller: SkedAppApiBundle:Api:getCategories}

sked_app_api_get_services:
    pattern:  /api/get/services/{session}/{id}
    defaults: { _controller: SkedAppApiBundle:Api:getServices , id: 1}
    requirements:
       id: \d+

sked_app_api_search_consultants:
    pattern:  /api/get/search/{session}/{category}/{service}/{address}/{date}/{lat}/{long}/{page}
    defaults: { _controller: SkedAppApiBundle:Api:searchConsultant, page: 1 }

sked_app_api_register_customer:
    pattern:  /api/get/register/{session}/{firstName}/{lastName}/{mobile}/{password}/{email}
    defaults: { _controller: SkedAppApiBundle:Api:registerCustomer}

sked_app_api_login_customer:
    pattern:  /api/get/login/{session}/{email}/{password}
    defaults: { _controller: SkedAppApiBundle:Api:login}

sked_app_api_get_consultant:
    pattern:  /api/get/consultant/{id}
    defaults: { _controller: SkedAppApiBundle:Api:getConsultant , id: 1}
    requirements:
       serviceId: \d+

sked_app_api_get_consultants:
    pattern:  /api/get/consultants/{serviceId}
    defaults: { _controller: SkedAppApiBundle:Api:getConsultants , serviceId: 1}
    requirements:
       serviceId: \d+

sked_app_api_geo_encode_address:
    pattern:  /api/geocode/address
    defaults: { _controller: SkedAppApiBundle:Api:geoEncodeAddress }

