sked_app_api_get_init:
    pattern:  /api/get/init
    defaults: { _controller: SkedAppApiBundle:Api:init }

sked_app_api_get_categories:
    pattern:  /api/get/categories/{session}
    defaults: { _controller: SkedAppApiBundle:Api:getCategories}

sked_app_api_get_services:
    pattern:  /api/get/services/{session}/{category}
    defaults: { _controller: SkedAppApiBundle:Api:getServices}

sked_app_api_search_consultants:
    pattern:  /api/get/search/{session}/{category}/{service}/{date}/{lat}/{lng}/{page}
    defaults: { _controller: SkedAppApiBundle:Api:searchConsultant, page: 1 }

sked_app_api_register_customer:
    pattern:  /api/get/register/{session}/{firstName}/{lastName}/{mobile}/{password}/{email}
    defaults: { _controller: SkedAppApiBundle:Api:registerCustomer}

sked_app_api_login_customer:
    pattern:  /api/get/login/{session}/{password}/{email}
    defaults: { _controller: SkedAppApiBundle:Api:login}

sked_app_api_get_consultant:
    pattern:  /api/get/consultant/{session}/{slug}
    defaults: { _controller: SkedAppApiBundle:Api:getConsultant }

sked_app_api_make_booking:
    pattern:  /api/get/book/{session}/{service}/{consultant}/{user}/{date}/{timeslot}
    defaults: { _controller: SkedAppApiBundle:Api:book }

