sked_app_api_get_init:
    pattern:  /api/get/init
    defaults: { _controller: SkedAppApiBundle:Api:init }

sked_app_api_get_categories:
    pattern:  /api/get/categories/{session}
    defaults: { _controller: SkedAppApiBundle:Api:getCategories}

sked_app_api_get_services:
    pattern:  /api/get/services/{session}/{id}
    defaults: { _controller: SkedAppApiBundle:Api:getServices , id: 1}
    requirements:
       id: \d+

sked_app_api_search_consultants:
    pattern:  /api/get/search/{session}/{category}/{service}/{address}/{date}/{lat}/{long}/{page}
    defaults: { _controller: SkedAppApiBundle:Api:searchConsultant, page: 1 }

sked_app_api_get_consultant:
    pattern:  /api/get/consultant/{id}
    defaults: { _controller: SkedAppApiBundle:Api:getConsultant , id: 1}
    requirements:
       serviceId: \d+

sked_app_api_get_consultants:
    pattern:  /api/get/consultants/{session}/{category}/{service}/{address}/{date}/{lat}/{lng}/{page}
    defaults: { _controller: SkedAppApiBundle:Api:searchConsultant , serviceId: 1}
    requirements:
       service: \d+

sked_app_api_geo_encode_address:
    pattern:  /api/geocode/address
    defaults: { _controller: SkedAppApiBundle:Api:geoEncodeAddress }

sked_app_api_register_customer:
    pattern:  /api/register/customer
    defaults: { _controller: SkedAppApiBundle:Api:registerCustomer }

sked_app_api_check_availability:
    pattern:  /api/check/consultant/available/{consultantId}/{bookingDateTime}
    defaults: { _controller: SkedAppApiBundle:Api:checkConsultantAvailable }
    requirements:
       consultantId: \d+

sked_app_api_make_booking:
    pattern:  /api/make/booking/{consultantId}/{serviceId}/{bookingDateTime}/{customerId}
    defaults: { _controller: SkedAppApiBundle:Api:makeBooking }
    requirements:
       consultantId: \d+
       serviceId: \d+
       customerId: \d+
