parameters:
#    sked_app_api.example.class: SkedApp\ApiBundle\Example

services:
#    sked_app_api.example:
#        class: %sked_app_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
